insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 97, 'MAXIMUM COLUMNS IN GROUP BY', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 99, 'MAXIMUM COLUMNS IN ORDER BY', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 100, 'MAXIMUM COLUMNS IN SELECT', 1664);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 101, 'MAXIMUM COLUMNS IN TABLE', 1600);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 1, 'MAXIMUM CONCURRENT ACTIVITIES', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 0, 'MAXIMUM DRIVER CONNECTIONS', NULL);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 20000, 'MAXIMUM STATEMENT OCTETS', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 20001, 'MAXIMUM STATEMENT OCTETS DATA', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 20002, 'MAXIMUM STATEMENT OCTETS SCHEMA', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 106, 'MAXIMUM TABLES IN SELECT', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 25000, 'MAXIMUM CURRENT DEFAULT TRANSFORM GROUP LENGTH', NULL);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 25001, 'MAXIMUM CURRENT TRANSFORM GROUP LENGTH', NULL);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 25002, 'MAXIMUM CURRENT PATH LENGTH', 0);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values (NULL, 25003, 'MAXIMUM CURRENT ROLE LENGTH', NULL);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 34, 'MAXIMUM CATALOG NAME LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 30, 'MAXIMUM COLUMN NAME LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 31, 'MAXIMUM CURSOR NAME LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 10005, 'MAXIMUM IDENTIFIER LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 32, 'MAXIMUM SCHEMA NAME LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 35, 'MAXIMUM TABLE NAME LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 107, 'MAXIMUM USER NAME LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 25004, 'MAXIMUM SESSION USER LENGTH', 63);
insert into "information_schema"."sql_sizing" ("comments", "sizing_id", "sizing_name", "supported_value") values ('Might be less, depending on character set.', 25005, 'MAXIMUM SYSTEM USER LENGTH', 63);
