insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '1', 'Framework (SQL/Framework)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '2', 'Foundation (SQL/Foundation)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '3', 'Call-Level Interface (SQL/CLI)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '4', 'Persistent Stored Modules (SQL/PSM)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '9', 'Management of External Data (SQL/MED)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '10', 'Object Language Bindings (SQL/OLB)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '11', 'Information and Definition Schema (SQL/Schemata)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '13', 'Routines and Types Using the Java Programming Language (SQL/JRT)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '14', 'XML-Related Specifications (SQL/XML)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '15', 'Multi-Dimensional Arrays (SQL/MDA)', 'NO', NULL);
insert into "information_schema"."sql_parts" ("comments", "feature_id", "feature_name", "is_supported", "is_verified_by") values ('', '16', 'Property Graph Queries (SQL/PGQ)', 'NO', NULL);
